### ISSUE TITLE
宏碁笔记本选购 R7-6800h+3060 140w ddr5 16g内存 售价7699元

### ISSUE THREAD

**Issue by jifeng35** [Cloud0310/BUPT-Freshmen-Computer-Purchase-Guide#5]
2K 165hz 内屏 
2022/8/16 00:00:00开售 售价7699元 
以下是购买链接
渠道:京东自营
[https://item.m.jd.com/product/100023009339.html?utm_user=plusmember&gx=RnFixmRZPj2IzdRP--twX0BgRTyN8qJHQjb6&ad_od=share&utm_source=androidapp&utm_medium=appshare&utm_campaign=t_335139774&utm_term=CopyURL](url)

**Comment by Cloud0310** [comment]
![图片](https://user-images.githubusercontent.com/60375730/184629819-3475ad62-d8a6-4bb0-ba8c-9dd10d5b93a3.png)
屏幕是1080p还是2k？
